#  FireDM
#
#  multi-connections internet download manager, based on "pyCuRL/curl", and "youtube_dl""
#
#  :copyright: (c) 2019-2021 by Mahmoud Elshahat.
#  :license: GNU LGPLv3, see LICENSE for more details.
#
#  Module description:
#      github action to build binaries for windows and linux and attach it to latest release
#      this action will be triggered everytime a new release is made


name: build-release-binaries

# Controls when the action will run. 
on:
  # Triggers the workflow on new release creation
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: create binaries
        run: |

          echo building windows zip file ...
          cd ./FireDM/scripts/exe_build
          python3 ./exe-quickbuild.py

          echo building linux appimage file
          cd ..
          cd ./appimage
          python3 ./appimage-quickbuild.py

      # upload file to github release page
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './FireDM/scripts/appimage/FireDM*.AppImage ./FireDM/scripts/exe_build/FireDM*.zip'
